### PR TITLE
Bumped Newman version to v3.9.1

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by domenique** [comment]
Hi @kunagpal, @elssar Could you please approve this PR? We are facing some issues with an older version of newman and would like to the latest.

**Comment by domenique** [comment]
In fact could you please update to newman 3.9.3?

**Comment by kunagpal** [comment]
@domenique We'll be creating separate pull requests for each Newman version, so as to maintain continuity. 😄

**Comment by domenique** [comment]
way ahead of you, check my other PR :)

**Pull request merged**
