### PR TITLE
Upgraded to newman 3.9.3

### PR DESCRIPTION
**Pull request by domenique**
Hi please approve....

### CODE REVIEW

**Comment by roelandcooreman** [comment]
Could you please approve this version

**Comment by aseady** [comment]
PLEASE APPROVE!

**Comment by kunagpal** [comment]
@domenique This is blocked on https://github.com/postmanlabs/newman-docker/pull/91. Also, there are merge conflicts on this pull request. Could you resolve them after #91 is merged to develop? Thanks! 😄

**Comment by kunagpal** [comment]
Apologies for the delay, but @domenique @aseady @roelandcooreman v3.9.3 Docker images have been published. I'm closing this pull request.

**Pull request closed without merging**
