### PR TITLE
Wrote documentation

### PR DESCRIPTION
**Pull request by elssar**

### CODE REVIEW

**Comment by shamasis** [comment]
There is `elssar` in readme example.

**Comment by shamasis** [comment]
Also, if we run multiple counts of the image in parallel, will it conflict in the working directory?

**Comment by elssar** [comment]
> There is elssar in readme example.

As good a placeholder as any :expressionless: 

> Also, if we run multiple counts of the image in parallel, will it conflict in the working directory?

Will have to check, though off the bat the only thing I can think of is that if multiple docker instances are writing newman output to the same file.

**Comment by elssar** [comment]
@shamasis ran two instances in parallel, there weren't any conflicts other than the output file being overwritten. No problems if both instances output to separate files

**Pull request merged**
